packages:
  css:
    - name: 'owl.carousel'
      source:
        - path: 'node_modules/owl.carousel/src/scss/owl.carousel.scss'
        - path: 'node_modules/owl.carousel/src/scss/owl.theme.default.scss'
      target: 'assets/css/vendor'
      flatten: true
      compile: true
      prefix: true
    - name: 'whiteboard'
      source: 'scss/whiteboard.scss'
      target: 'assets/css/vendor'
      compile: true
      prefix: true
  js:
    - name: 'owl.carousel'
      source: 'node_modules/owl.carousel/dist/*.js'
      target: 'assets/js/vendor'
      flatten: true
    - name: 'particles.js'
      source: 'node_modules/particles.js/particles.js'
      target: 'assets/js/vendor'
      minify: true
    - name: 'typed.js'
      source: 'node_modules/typed.js/lib/*'
      target: 'assets/js/vendor'
      flatten: true

supportedBrowsers:
  - 'last 1 major version'
  - '>= 1%'
  - 'Android 2.3'
  - 'Android >= 4'
  - 'Chrome >= 35'
  - 'Edge >= 12'
  - 'Explorer >= 10'
  - 'Firefox >= 38'
  - 'iOS >= 8'
  - 'Opera >= 12'
  - 'Safari >= 8'

